
name: Release Encaludus

on:
  workflow_dispatch:

jobs:
  
  build-frontend:
    name: Build console frontend
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Get Console master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Frontend
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
        working-directory: ./frontend
      - run: yarn run build
        working-directory: ./frontend
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dist
          path: ./frontend/public/dist

  build-platform:
    name: Build platfrom specific packages
    needs: [build-frontend]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Build backend
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15.5
    - run: go build -o bin/bridge github.com/openshift/console/cmd/bridge
      env:
        GOFLAGS: '-mod=vendor'
    - name: Restore frontend-dist
      uses: actions/download-artifact@v2
      with:
        name: frontend-dist
        path: ./frontend/public/dist
    - name: Build 
      uses: actions/setup-node@v1
    - run: yarn install
      working-directory: ./encaludus
    - run: yarn run compile
      working-directory: ./encaludus
    - run: yarn run make     
      working-directory: ./encaludus
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-distro
        path: ./encaludus/out/make/zip/**/*.zip
