
name: Release Encaludus

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build backend
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15.5
    - run: ./build-backend.sh
    - name: Build Frontend
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ./build-frontend.sh
    - name: Build 
      uses: actions/setup-node@v1
    - run: |
         yarn install
         yarn run compile
         yarn run make     
      working-directory: ./encaludus

