
name: Release Encaludus

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  
  build-frontend:
    name: Build console frontend
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Get Console master
        uses: actions/checkout@v2
        with:
          repository: openshift/console
          ref: master
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Frontend
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
        working-directory: ./frontend
      - run: yarn run build
        working-directory: ./frontend
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dist
          path: ./frontend/public/dist

  build-platform:
    name: Build platfrom specific packages
    needs: [build-frontend]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Build backend
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15.5
    - run: go build -o bin/bridge github.com/openshift/console/cmd/bridge
      env:
        GOFLAGS: '-mod=vendor'
    - name: Restore frontend-dist
      uses: actions/download-artifact@v2
      with:
        name: frontend-dist
        path: ./frontend/public/dist
    - name: Build 
      uses: actions/setup-node@v1
    - run: yarn install
      working-directory: ./encaludus
    - run: yarn run compile
      working-directory: ./encaludus
    - run: yarn run make     
      working-directory: ./encaludus
    - name: Upload zip
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/gorkem/console/releases/35117499/assets{?name,label}
        release_id: 35117499
        asset_path: ./encaludus/out/make/zip/**/*.zip
        asset_name: encaludus-${{ matrix.os }}-$$.zip
        asset_content_type: application/zip 
        max_releases: 7 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
